version: "3.8"

services:
  postgres:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: foodmastr
    build: ./postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis_db
    image: redis
    ports:
      - "6379:6379"
