export enum AUTH {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
  EMAIL_TAKEN = "EMAIL_TAKEN",
}

export enum GENERAL {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
